bulk_update 📦:
  - "scripts/migrations/**"
data:api 🐇:
  - "api/**"
data:browsers 🌍:
  - "browsers/**"
data:css 🎨:
  - "css/**"
data:html 📄:
  - "html/**"
data:http 🚠:
  - "http/**"
data:js 📟:
  - "js/**"
data:mathml ➗:
  - "mathml/**"
data:svg 🖌:
  - "svg/**"
data:webdriver 🏎:
  - "webdriver/**"
data:webext 🎲:
  - "webext/**"
data:xpath 🛤:
  - "xpath/**"
data:xslt 🚜:
  - "xslt/**"
dependencies ⛓:
  - "package-lock.json"
  - "package.json"
docs ✍️:
  - "*.md"
linter 🏡:
  - "test/**"
