language: node_js
before_script:
  - npm install jsonlint -g
  - npm install ajv-cli -g
script:
  - find . -name \*.json  | xargs -I {} jsonlint -q {}
  - ajv validate -s compat-data.schema.json -d **/*.json
notifications:
  email: false
