# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ ] # Test on push to every branch
  pull_request:
    branches: [ ] # Test on push to every branch

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        # TODO: hoist to 10.x when we bump the version supported in #5931
        node-version: [ 8.x ]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2-beta
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm test
